# Generated by Django 5.0 on 2024-01-25 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0001_initial'),
        ('mentorManagement', '0001_initial'),
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCompleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.CharField(default='pending', max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.batch')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.instructor')),
            ],
        ),
    ]
