# Generated by Django 5.0 on 2024-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorManagement', '0002_batchcompleterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcompleterequest',
            name='is_complete',
            field=models.CharField(choices=[('pending', 'Pending'), ('aproved', 'Aproved'), ('not_aproved', 'Not Aproved')], max_length=30),
        ),
    ]
