# Generated by Django 5.0 on 2024-01-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialMediaRefCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('redirect', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('0', 'Not Contacted'), ('1', 'Not Answered'), ('2', 'Follow Up'), ('3', 'Not Interested'), ('4', 'Converted')], default='0', max_length=1)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('conversation_record', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateField(blank=True, editable=False, null=True)),
                ('assigned_sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='userManagement.salesperson')),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='CRM.socialmediarefcode')),
            ],
        ),
    ]
